version: '3'
services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 3000:80
    links:
      - db
    volumes:
      - ./mediawiki:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql